version: "3.6"

services:
  app:
    container_name: noty_app
    build: ./
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - database
    volumes:
      - type: bind
        source: .
        target: /var/www/app
  database:
    # image: postgres
    build:
      context: ./docker/postgresql
    ports:
      - "5434:5432"
    container_name: noty_database
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        source: noty_postgres
        target: /var/lib/postgresql
    networks: 
      - default
networks: 
  default:
    driver: bridge
volumes:
  noty_postgres: