version: "3.6"

services:
  app:
    container_name: red_app
    build: ./
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - redis
      - database
  redis:
    image: redis:alpine
    container_name: red_redis
    volumes:
      - type: volume
        source: red_redis
        target: /data
    networks: 
      - default
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379", "--requirepass","secret", "--appendonly","yes"]
  database:
    build:
      context: ./docker/postgresql
    ports:
      - "5434:5432"
    container_name: red_database
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        source: red_postgres
        target: /var/lib/postgresql
    networks: 
      - default
networks: 
  default:
    driver: bridge
volumes:
  red_redis:
  red_postgres: