version: '3.6'

services: 
  database:
    build:
      context: ./docker/postgresql
    ports:
      - "5434:5432"
    container_name: ed_database
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        source: ed_postgres
        target: /var/lib/postgresql
    networks: 
      - default
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ed_rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE: 'secret_cookie'
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    volumes:
      - ./docker/rabbitmq:/usr/src/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    networks: 
      - default
  app:
    build: 
      context: .
    depends_on:
      - database
      - rabbitmq
    links: 
      - database
      - rabbitmq
    container_name: ed_app
    restart: unless-stopped
    environment:
        NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks: 
      - default
volumes:
  ed_postgres:
networks: 
  default:
    driver: bridge