version: '3.6'

services: 
  database:
    # image: postgres
    build:
      context: ./docker/postgresql
    ports:
      - "5434:5432"
    container_name: pure_database
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        source: pure_database
        target: /var/lib/postgresql
    networks: 
      - default
  app:
    build: 
      context: .
    depends_on:
      - database
    container_name: pure_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - default
    links:
      - database
volumes:
  pure_database:
networks: 
  default:
    driver: bridge