version: '3.6'

services: 
  elasticsearch:
    container_name: nacode_elasticsearch
    build:
      context: ./docker/elasticsearch
    volumes:
      - type: bind
        source: ./docker/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - type: volume
        source: nacode_elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks: 
      - default
  kibana:
    container_name: nacode_kibana
    build:
      context: ./docker/kibana/
    ports:
      - "5601:5601"
    restart: unless-stopped
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      # - logstash
    volumes:
      - type: bind
        source: ./docker/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true 
    networks: 
      - default
  apm-server:
    container_name: nacode_apm_server
    build:
      context: ./docker/apm
    ports:
        - "127.0.0.1:${APM_SERVER_PORT:-8200}:8200"
        - "127.0.0.1:${APM_SERVER_MONITOR_PORT:-6060}:6060"
    volumes:
      - type: bind
        source: ./docker/apm/config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
    depends_on:
      - elasticsearch
      - kibana
    links:
      - kibana
      - elasticsearch
    networks: 
      - default
  database:
    build:
      context: ./docker/postgresql
    ports:
      - "5434:5432"
    container_name: nacode_database
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        source: nacode_database
        target: /var/lib/postgresql
    networks: 
      - default
  app:
    build: 
      context: .
    depends_on:
      - database
      - elasticsearch
      # - logstash
      - apm-server
    container_name: nacode_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    networks: 
      - default
    links:
      - database
      - apm-server
  # logstash:
  #   container_name: nacode_logstash
  #   build:
  #     context: ./docker/logstash
  #   volumes:
  #     - type: bind
  #       source: ./docker/logstash/config/logstash.yml
  #       target: /usr/share/logstash/config/logstash.yml
  #       read_only: false
  #     - type: bind
  #       source: ./docker/logstash/pipeline
  #       target: /usr/share/logstash/pipeline
  #       read_only: false
  #   environment:
  #     - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
  #   depends_on:
  #     - elasticsearch
  #   links:
  #     - elasticsearch
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   networks: 
  #     - default
volumes:
  nacode_database:
  nacode_elasticsearch:
networks: 
  default:
    driver: bridge